### ISSUE TITLE
populate with git history if project isn't new

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/changelog-init#7]
@bcomnes What do you think about populating the change log with all version tags found for projects that aren't brand-new? The content could be a list of commit messages for each one. This kind of violates the "don't let your friends dump git logs into CHANGELOGs" tenet of http://keepachangelog.com/ but it would be useful for getting an older project up to speed.

**Comment by bcomnes** [comment]
I think its forgivable in the act that you are now keepingachangelog, but yeah, that would be cool and actually make this module do something a bit more interesting.

**Comment by ungoldman** [comment]
closing issue, going to archive this 🏄
